<?php

use App\Models\User;
use Illuminate\Support\Facades\DB;

// specs/03-domain-model.md §1, D-009: UUIDv7 keys generated by the application,
// stored as PostgreSQL uuid.
it('stores the users key as a PostgreSQL uuid', function () {
    $type = DB::scalar(
        "select data_type from information_schema.columns where table_name = 'users' and column_name = 'id'"
    );

    expect($type)->toBe('uuid');
});

it('generates version 7 UUIDs in the application', function () {
    $user = User::factory()->create();

    expect($user->getKey())->toMatch('/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/');
    expect(User::query()->whereKey($user->getKey())->exists())->toBeTrue();
});
